sudo: false
language: java
jdk: openjdk8

cache:
  directories:
    - $HOME/.m2

stages:
  - name: test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: deploy
      jdk: openjdk8
      script:
        - mvn -f yamcs-maven-plugin site:site
        - mkdir -p docs
        - touch docs/.nojekyll
        - cp -r target/site docs/yamcs-maven-plugin
      deploy:
        provider: pages
        skip-cleanup: true  # Keep HTML files generated during 'script'
        local-dir: docs
        github-token: $GITHUB_TOKEN
        keep-history: false  # Force-update single commit on gh-pages branch
