name: GitHub Pages

on:
  push:
    branches:
      - stable

jobs:
  sphinx:
    name: Update website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up sphinx
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
      - name: Generate documentation
        run: |
          cd docs
          make html
          touch _build/html/.nojekyll
      - name: Deploy to GitHub Pages
        uses: maxheld83/ghpages@v0.2.1
        env:
          GH_PAT: ${{ secrets.ACTIONS_PAT }}
          # Follow: https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/31266/
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_DIR: docs/_build/html
